name: micro_app_onboarding
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  micro_core:
    path: ../micro_core
  micro_commons_design_system:
    path: ../micro_commons_design_system
  micro_commons_deps:
    path: ../micro_commons_deps
  micro_commons_infra:
    path: ../micro_commons_infra

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/