name: base_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.5

  micro_core:
    path: ../micro_core
  micro_commons_design_system:
    path: ../micro_commons_design_system
  micro_app_login:
    path: ../micro_app_login
  micro_app_onboarding:
    path: ../micro_app_onboarding
  micro_app_bills:
    path: ../micro_app_bills
  micro_app_settings:
    path: ../micro_app_settings

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: Gotham
    fonts:
      - asset: assets/fonts/GothamBold.ttf
      - asset: assets/fonts/GothamMedium.ttf
      - asset: assets/fonts/GothamLight.ttf  
  - family: Allrox
    fonts:
      - asset: assets/fonts/Allrox.ttf  
        
flutter_native_splash:
  color: "#282A36"
  image: ./assets/images/billy.png

