name: micro_commons_deps
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_hooks: ^0.18.3
  flutter_riverpod: ^1.0.3
  equatable: ^2.0.3
  cloud_firestore: ^3.1.14
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  faker: ^2.0.0
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
