name: micro_commons_design_system
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  micro_commons_deps:
    path: ../micro_commons_deps

flutter:

dev_dependencies:
  flutter_test:         
    sdk: flutter
  flutter_lints: ^1.0.0
